### ISSUE TITLE
Issue with prefiltering

### ISSUE THREAD

**Issue by rsiani** [ranwez/MACSE_V2_PIPELINES#10]
HI,
I wanted to run omm_macse on ~ 1200 sequences. 

`omm_macse_v12.01.sif --out_dir macseC2 --out_file_prefix C --in_seq_file C_all.ffn --genetic_code_number 11 --java_mem 2000m --min_percent_NT_at_ends 0.8 --aligner_extra_option "--thread 3 --retree 1"`

However I see from the program std.out and the final alignment that over 200 sequences are discarded directly from the start. 

_848	sequences with genetic code	The_Bacterial_Archaeal_and_Plant_Plastid_Code_

I also tried running with -_-no_prefiltering_ option but the same happen. 

Does the program remove identical sequences or what else is going on? I already dereplicated the sequences prior to alignment

**Comment by ranwez** [comment]
Hi,
I'm sorry you are facing problems while using MACSE. It is possible that some of your sequences are very short and are only present in the trimmed extremities of the alignment (min_percent_NT_at_ends 0.8 remove the gappy extremities of your alignment until reaching sites with at least 80% of non gap see). I don't know what you are actually trying to align but if it is barcoding related you may be interested by our dedicated [barcoding pipeline](https://github.com/ranwez/MACSE_V2_PIPELINES/tree/master/MACSE_BARCODE). As detailed in the readme_output.txt OMM_MACSE, OMM_MACSE output provides two csv text files (XXX_maskHomolog_stat.csv XXX_maskFull_stat.csv ) detailing the impact of the filtering steps  on each sequence . 

However I agree that the above explanations could explain that some sequences are discarded during the alignment/filtering process but not why they are discarded from the begining (the only idea that came to my mind is that maybe some of your sequences have length zero, maybe due to previous pre-treatment). 

If these first feedbacks are not sufficient to help you fixing your problem please do not hesitate to send me an email with your input sequence fasta file and I will do my best to try to figure out what is going on and to provide you a solution.

**Comment by rsiani** [comment]
Hi, 
thanks for the lighting fast reply. 

Since the sequences are removed directly at "input arrival" they are not included in the stat files. But I just tried another codon msa and it also filtered out a similar number of sequences, so I guess the problem must come from my side. 

I have looked again in the input sequences and I can't yet place the issue, as all sequences are of similar length and I selected them based on stringent homology value. Might be an issue with the direction of the sequence? (but it's genomic cds so I guess it shouldn't be the case).

 But so far looks like its not a macse problem, so I will close this issue. 

Thanks for the assistance!
