### ISSUE TITLE
file does not exist

### ISSUE THREAD

**Issue by aguang** [ranwez/MACSE_V2_PIPELINES#2]
I am having another issue with running OMM_MACSE in a Singularity container although I think it is related to the `get_in_file_param()` function.

When I try to run OMM_MACSE, I get the error that `all.fa` does not exist:

```
[aguang@login004 msa]$ singularity run omm_macse_v10.02.sif --in_seq_file all.fa  --out_dir omm_macse --out_file_prefix all_macse --java_mem 4000m


Problem with option --in_seq_file, File all.fa does not exist

This script aligns sequences using: 1) MACSE pre-filtering, 2) MACSE alignment to find frameshifts, 3) MAFFT for aligning the resulting AA sequences, and 4) HMMcleaner for cleaning resulting alignments.

your command line is incorrect please check your options
 usage example:
S_OMM_MACSE_V10.02.sh --out_dir out_dir --out_file_prefix PREFIX --in_seq_file seq_file.fasta [--genetic_code_number code_number] [--alignAA_soft MAFFT/MUSCLE/PRANK] ][--aligner_extra_option "--localpair --maxiterate 1000"] [--min_percent_NT_at_ends 0.7] [--out_detail_dir SAVE_DETAILS/] [--in_seq_lr_file less_reliable_seq_file.fasta] [--java_mem 500m] [--no_prefiltering] [--no_FS_detection] [--no_filtering] [--no_postfiltering] [--min_seqToKeepSite] [--replace_FS_by_gaps] [--save_details] [--debug]


For further details please check the documentation on MACSE website: https://bioweb.supagro.inra.fr/macse
```

However it very clearly does:

```
[aguang@login004 msa]$ ls
all.fa  omm_macse_v10.02.sif
```

I see that it is for some reason triggering the error message in [`get_in_file_param()`](https://github.com/ranwez/MACSE_V2_PIPELINES/blob/master/UTILS/S_utilIO.sh), however I cannot figure out why, since the file is clearly there.

**Comment by ranwez** [comment]
The test check if the parameter is a regular file (as opposed to a directory or device file).

Instead of "ls" could you please try "ls -l" to display full information on "all.fa" (so that we are certain that all.fa is indeed a regular file and not a directory containing all your fasta files). If you got multiple fasta files you cannot launch them all using a directory name, a solution to align them all is  to use a bash for loop, something like :

for f in *.fa; do filePrefix=$(basename $f  .fa); singularity run omm_macse_v10.02.sif --in_seq_file $f  --out_dir omm_macse_$(filePrefix) --out_file_prefix $(file_prefix) --java_mem 4000m; done
and if working on a cluster you should probably wrap the singularity instruction of this for loop within a  job submission instruction.

If this does not solve your problem please contact me directly using my email (vincent.ranwez@supagro.fr) so that we can try to solve your issue rapidly (e.g via a short visioconference meeting)

**Comment by zcalamari** [comment]
Hello, I am having this same problem with the ALFIX singularity container. I've checked the fasta file that I am trying to run, and it is a regular file. The file is in the same directory with the singularity container, and although there are other fasta files in the directory, I am specifying a single fasta file for a test run of the pipeline (I have also tested it as part of a bash loop and had a similar result). Was there a solution to this issue that worked?

**Comment by ranwez** [comment]
Hello,

The problem seems to be related to folders available on the HPC cluster that are not fully visible from within the singularity container. I think that it is a problem during the installation of singularity by HPC administrators (but I’m not sure). This seems to be a problem similar to the one discussed [here ](https://singularity.lbl.gov/archive/docs/v2-3/faq#troubleshooting). 

The way we "solved" it with Aguang was by using the /tmp folder that is present on all linux machine/cluster. So she i) created a temporary folder in /tmp, ii) copy the singularity container and input file in it, and iii) run the container from the temporary folder and it worked fine.

A much better solution would be to fix the folder access problem. This could probably be done by binding the folder of your clusters to folders (having the same names or not) available on the singularity container using the bind option, [see examples here](https://hpc.nih.gov/apps/singularity.html).

 To get the same folder names within the container (and do the bind) you probably have to generate your own singularity container after having modified the [ALFIX singularity recipie](https://github.com/ranwez/MACSE_V2_PIPELINES/blob/master/MACSE_ALFIX/V01_FREEZED/MACSE_ALFIX_V01_sing_3.3.def)  by adding a few lines to create the folders of your cluster that you need to access within the container. You can get an example of this in the [OMM_MACSE recipe](https://github.com/ranwez/MACSE_V2_PIPELINES/blob/master/OMM_MACSE/OMM_MACSE_V10.02_sing_3.3.def)  where I created three folders to get it working on a HPC cluster:
```
# folders needed for the migale cluster
mkdir -p /projet/extern/save/; mkdir -p /projet/montpellier/work; mkdir -p /projet/montpellier/work
```
Note that in my case creating these folders was enough, so I assumed that the binding part was done by the HPC administrators, if you can get some help from one of your cluster system administrators this will probably make thing muche easier.

Please let me know if it is working from the /tmp folder (which is a simple workaround). If you try to adapt the recipe to your cluster it will also be great to know if it really solve the problem. 

If this doesn't solve your problem do not hesitate to contact me by email so that we can arrange a short visioconference meeting to try to solve it together.

I'm really sorry for the inconvenience.

**Comment by zcalamari** [comment]
Thanks for the quick response, I appreciate the help! I'll talk to my cluster administrators and let you know how things work out.

**Comment by zcalamari** [comment]
Hi again, the advice from my cluster administrator was to set the SINGULARITY_BINDPATH variable to include the folder where my sequences were, with **export SINGULARITY_BINDPATH="/path/to/fasta"**. This seems to have done the trick!

**Comment by ranwez** [comment]
Thank you for the feedback. I think this will be very useful to other users and I will include this in the help pages

**Comment by drabe004** [comment]
Curious whether using the bioconda recipe nullifies this issue. 
I'm having the same problem except weirdly if I run MACSE on a single fasta file, it works, 
If I put it in a loop it says the files are unreadable

**Comment by ranwez** [comment]
@drabe004 this is indeed really strange ...  My first guess would be that the reading right associated to the file use for the single file test differs from the reading right associated to the fasta files you try to access in the for loop (either the file themselves, which you can check with ls -l) or the folder on which these files are stored. You could try to replace MACSE by an other command (a simple head $file could to the trick) to test if the problem is related to MACSE or not. I hope you will be able to fix the problem, let me know ...

**Comment by drabe004** [comment]
Hmmm I didn't try the $file trick, but I did try binding the directories and changing file permissions. 
I ended up just writing a brute force script with a text editor (a single line for each file command. This worked... which still makes no sense to me. Just replying on here in case anyone else has this issue. I think it might be a Singularity issue (oh well!)
