### ISSUE TITLE
which program is parameter -alphabet_AA applicable?

### ISSUE THREAD

**Issue by csgenomics-admin** [ranwez/MACSE_V2_PIPELINES#3]
Hello,
Could you help clarify whether or not the `-alphabet_AA` parameter is intended for us in the `alignSequences` program (or not)?

If I run the following command, the program executes successfully:
```
java -jar macse.jar -prog alignSequences -out_AA {aa.out} -out_NT {nt.out} -seq {input.fa}
```

Likewise, if I run the `translateNT2AA` program, and add in the `-alphabet_AA` parameter with a non-default option, the program completes without error:
```
java -jar macse.jar -prog translateNT2AA -out_AA {aa.translate.out} -seq {input.fa} -alphabet_AA Dayhoff_6
```

However, if I run the `alignSequences` program and add the `-alphabet_AA` parameter, I get an error
```
java -jar macse.jar -prog alignSequences -out_AA {aa.out} -out_NT {nt.out} -seq {input.fa} -alphabet_AA Dayhoff_6
```

This error is repeated for different input .fa sequences, and different `alphabete_AA` options:
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 15
	at programs.align.NodeST.getChild(NodeST.java:80)
	at programs.align.SuffixTree.buildSuffixTree(SuffixTree.java:194)
	at programs.align.SuffixTree.<init>(SuffixTree.java:54)
	at programs.align.Aligner.computeInitialSequenceDistanceMEM(Aligner.java:129)
	at programs.align.Aligner.alignMultiSequences(Aligner.java:78)
	at programs.align.Aligner.alignSequenceSet(Aligner.java:48)
	at programs.align.AlignSequences.execute(AlignSequences.java:89)
	at cli.CLI_program.parse(CLI_program.java:110)
	at cli.CLI_api.parse(CLI_api.java:234)
	at main.MacseMain.parse(MacseMain.java:111)
	at main.MacseMain.filterCommands(MacseMain.java:54)
	at main.MacseMain.main(MacseMain.java:203)
```

Because the `alphabet_AA` parameter was listed in both programs, I assumed it would be applicable to both program. Perhaps I am mistaken and should not be applying it for the `alignSequences` program?

Thank you for your assistance

**Comment by ranwez** [comment]
Hello,
this is indeed a bug. The AA_alphabet is not correctly handled when using it to compute initial pairwise distance. This seems easy to fix, I will try to fix it rapidly and let you know when it is done.

Thanks for taking time to report the issue.

**Comment by csgenomics-admin** [comment]
Good afternoon Vincent,
I was curious if you have made any progress in resolving this issue?
Thank you, and happy new year!

**Comment by ranwez** [comment]
Hello, and Happy new year!

The bug is now fix. The latest release of MACSE including this fix is availble [here](https://bioweb.supagro.inra.fr/macse/index.php?menu=releases ). However I'm not sure that there will be a major impact of using different compressed alphabet for the alignment since this is just used to detect some higly conserved regions and (try to) speed up (a little bit) the alignment process. Using a different compressed alphabet, could have more impact on the filteringNonHomolousFragment, and anyway it was a bug that need to be fix ;)

Note that since this option is not used in MACSE pipelines, I do not plan to update the pipeline/container to take it into account. Only the standalone MACSE jar file is updated so far. For issue regarding MACSE, and not the pipelines build using it, it could be better to use the [MACSE github page](https://github.com/ranwez/macse_v2/issues) rather than this one.

Thank you very much for having taking time to report the issue and don't hesitate to contact me by email to give me some feedbacks regarding the impact of the different compressed alphabet on your work.

**Comment by csgenomics-admin** [comment]
Terrific. I appreciate the update and thank you for your input regarding the possibly limited utility with changing the alphabet. 
I use MACSE as a standalone .jar file (not in a pipeline), so I'd be happy to send further requests to a different link. However, please note that the current link you've suggested in your previous response is broken (https://github.com/ranwez/macse_v2/issues). 
Thanks you for continuing to support a wonderful piece of software
