### ISSUE TITLE
No FS option

### ISSUE THREAD

**Issue by asumann** [ranwez/MACSE_V2_PIPELINES#5]
Hi,

My only aim is having easy codon alignment without back-translation. And the alignment output file I need should have gaps in triplets only (which will be the input for another tool). Is it possible to align sequences without "!" insertion for frameshifts? If I replace ! with - this will not be useful for me since I can only have gaps in triplets. 

I can insert three -  per frameshift site, or delete ! . But then, alignment lengths will not be equal, and this is not favorable as well. If there would be a -noFS option which would do codon alignment without detecting frameshift sites, this would solve the problem for me.

Any suggestions?

Thanks a million!

**Comment by ranwez** [comment]
Hi,

the final output files (XXX__final_align_NT.aln XXX__final_align_AA.aln) do not contain frameshift or stop symbols, but some intermediate files with frameshifts are also provided (see readme_output.txt in the output folder for detail regarding the output files) so it seems like you open one of this intermediate files instead of the final ones.

By default each codon containing a frameshift is replaced by a gap codon "---" as you wish. Alternatively it could also be replaced by "NNN" if you prefer (see the doc here for more detail [here](https://bioweb.supagro.inra.fr/macse/index.php?menu=docPipeline/docPipelineHtml))

bests,

Vincent Ranwez

**Comment by asumann** [comment]
Perfect! It run all fine using OMM pipeline.
