### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by simone-says** [ranwez/MACSE_V2_PIPELINES#7]
I keep getting this error when trying to run MACSE on my university's HPC:

`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at align.ProfileAligner.<init>(ProfileAligner.java:120)
	at align.CodingMSA.<init>(CodingMSA.java:64)
	at align.CodingMSA.buildAlignmentReliable(CodingMSA.java:633)
	at align.CodingMSA.run(CodingMSA.java:659)
	at utils.MacseMain.main(MacseMain.java:426)
srun: error: cn28: task 0: Exited with exit code 1`

This is what the log files say before failing:
`13	 sequence(s) with genetic code	The_Standard_Code
Build draft alignment using greedy strategy based on UPGMA tree`

This is my job script (an array- one job per concatenated FASTA):

`#!/bin/bash
#SBATCH --job-name=MACSE
#SBATCH --array=1-7426
#SBATCH --mem=350000
#SBATCH --cpus-per-task=12
#SBATCH --time=2-00:00:00
#SBATCH --export=ALL

module load anaconda3
source /packages/anaconda3/2022.10/etc/profile.d/conda.sh
conda activate macse

busco_id=$(sed -n "$SLURM_ARRAY_TASK_ID"p /projects/tollis_lab/crocs/analysis/BUSCO_croc.bird.turt/01_BUSCO_meta/busco_nt_merged/mafft_croc_input)
cd /projects/tollis_lab/crocs/analysis/BUSCO_croc.bird.turt

srun macse -prog alignSequences -seq 01_BUSCO_meta/busco_nt_merged/${busco_id} -out_NT 02_macse/${busco_id}_outNT.fa -out_AA 02_macse/${busco_id}_outAA.fa &&
srun macse -prog exportAlignment -align 02_macse/${busco_id}_outNT.fa -codonForInternalStop NNN -codonForInternalFS --- -charForRemainingFS - -out_NT 02_macse/${busco_id}_NT.macse.fa -out_AA 02_macse/${busco_id}_AA.macse.fa`

I've tried different amounts of CPUs and have increased the memory to the max. Am I misspecifying something?

**Comment by ranwez** [comment]
I think that your script request a node with a lot of available memory but don't actually allow java/macse to use this memory, hence the error message from Macs.

To provide more memory to MACSE you need to use the Xmx option of java. This problem occurs with other java programs wrapped via conda, see discussions [here](https://github.com/MonashBioinformaticsPlatform/RNAsik-pipe/issues/36) and [there](https://stackoverflow.com/questions/44176793/how-does-one-set-the-ram-and-cpu-parameters-for-java-programs-running-in-an-anac).

You should probably use macse directly without relying on the conda wrapper. All you need is a java interpreter available on your cluster. You probably have one that you can load using the module load instruction. However, if java is not available on your cluster you could use a conda environment for java ([many are available](https://anaconda.org/search?q=java)) and then call macse using java (either locally available or available through a conda environment).

You need to download the macse jar file available [here](https://bioweb.supagro.inra.fr/macse/index.php?menu=releases). 

This will only slightly change your script:
(assuming that you save the latest release of macse_v2.06.jar in the same directory as your script.)

module load anaconda3
source /packages/anaconda3/2022.10/etc/profile.d/conda.sh
conda activate macse

===> module load java
(or something equivalent, module avail should give you the correct module name for loading java/jre)

srun macse -prog alignSequences -seq 01_BUSCO_meta
===> srun java -jar -Xmx600m macse_v2.06.jar -prog alignSequences -seq 01_BUSCO_meta
(-Xmx600m allocate 600 Mo for java/macse, you can adjust this value to your needs)

I hope this will help you solve your problem and use macse on your university's HPC. Please feel free to ask me if you encounter any other problems.

**Comment by simone-says** [comment]
I was trying to use macse in a Snakemake pipeline, hence using conda. Is there a way around this while still using conda?

**Comment by ranwez** [comment]
Hi,

**setting memory with the macse conda package**
I checked the source code of the [conda wrapper for macse](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/macse/macse.py) (I'm not the author of this conda recipe) and it is indeed capable of handling java memory options (lines 50 to 62 of the above wrapper script)

so having load the macse conda package, you simply need to add the Xmx option to your srun command:
srun macse -prog alignSequences -seq 01_BUSCO_meta/busco_nt_merged/${busco_id} -out_NT 
=> srun macse -Xms2g -Xmx2g -prog alignSequences -seq 
(set Xmx and Xmx according to your need)
and it should work just fine. 

**memory issues, very long sequences and frequent errors**
In the wrapper script default_jvm_mem_opts = ['-Xms512m', '-Xmx1g']) which is already quite large and should be sufficient in most case except for very long CDS. If MACSE still crash could you check that you don't have one very long sequence in your input file. According to your command you seems to align each Busco gene separately which is fine meanwhile your directory/file name include concatenate and mafft in their names so I'm not sure what your doing. If you attempt a superMatrix approach gene should be aligned individually and then the alignments concatenate. If you concatenate gene sequences (to get one huge sequence per species) first and then try to align them this will indeed require huge memory and probably never work; but it also make no real sense to do that since it would allow nucleotides from one Busco gene to be place in front of nucleotide of a different Busco gene during the alignment process 

Note also that MACSE expect coding sequences only so you should provide CDS and not the full gene sequences which include UTR and intro and is usually much longer.

I don't say that you are doing any of these errors but since it is errors that I have already encountered and can explain memory issues I prefer to mention these possibles errors just in case.

**using a more recent version of macse using shell block**
Note that this is an old version of MACSE (the alignment should still be correct but you don't have the new functionalities of the v2 release). However if you want to use a newer release you can do it with conda and snakemake since you can use conda to get a java environment and in your snakemake rule use a shell block calling macse 
shell:
     java -jar -Xmx600m macse_v2.06.jar -prog alignSequences -seq 01_BUSCO_meta

This imply to get the macse jar file preloaded. I agree that though this would work you loose part of the software version traceability you get with pure conda/snakemake.

**Conclusion**
I hope this will solve your problems, otherwise could you send me one of the problematic fasta file so that I could try to identify the problem and why your dataset require so much memory.

Meanwhile I will try to post an updated version of the macse conda package (with the latest macse release) but this could take some times.

**Comment by simone-says** [comment]
Thank you so much! I got the script to run by specifying the memory as you suggested and that is working great. 

I am aligning the same genes across many species and keeping them all separate to generate gene trees. The mafft_croc_input file is just a .txt file input list, I am using the same species that I previously aligned with MAFFT but we are switching to MACSE. BUSCOs only include CDS but thank you for the suggestion. I will add MACSE to the Snakemake pipeline and test it out after the current MACSE alignment finishes. Thanks again!
